package com.herbertgao.telegram.database.entity;

import java.time.LocalDateTime;

public class ExamDate extends ExamDateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.exam_year
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private Integer examYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.exam_desc
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private String examDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.short_desc
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private String shortDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.exam_begin_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private LocalDateTime examBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.exam_end_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private LocalDateTime examEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.exam_year_begin_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private LocalDateTime examYearBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.exam_year_end_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private LocalDateTime examYearEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.is_delete
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.exam_year
     *
     * @return the value of exam_date.exam_year
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public Integer getExamYear() {
        return examYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.exam_year
     *
     * @param examYear the value for exam_date.exam_year
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setExamYear(Integer examYear) {
        this.examYear = examYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.exam_desc
     *
     * @return the value of exam_date.exam_desc
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public String getExamDesc() {
        return examDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.exam_desc
     *
     * @param examDesc the value for exam_date.exam_desc
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setExamDesc(String examDesc) {
        this.examDesc = examDesc == null ? null : examDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.short_desc
     *
     * @return the value of exam_date.short_desc
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public String getShortDesc() {
        return shortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.short_desc
     *
     * @param shortDesc the value for exam_date.short_desc
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc == null ? null : shortDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.exam_begin_date
     *
     * @return the value of exam_date.exam_begin_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public LocalDateTime getExamBeginDate() {
        return examBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.exam_begin_date
     *
     * @param examBeginDate the value for exam_date.exam_begin_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setExamBeginDate(LocalDateTime examBeginDate) {
        this.examBeginDate = examBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.exam_end_date
     *
     * @return the value of exam_date.exam_end_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public LocalDateTime getExamEndDate() {
        return examEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.exam_end_date
     *
     * @param examEndDate the value for exam_date.exam_end_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setExamEndDate(LocalDateTime examEndDate) {
        this.examEndDate = examEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.exam_year_begin_date
     *
     * @return the value of exam_date.exam_year_begin_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public LocalDateTime getExamYearBeginDate() {
        return examYearBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.exam_year_begin_date
     *
     * @param examYearBeginDate the value for exam_date.exam_year_begin_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setExamYearBeginDate(LocalDateTime examYearBeginDate) {
        this.examYearBeginDate = examYearBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.exam_year_end_date
     *
     * @return the value of exam_date.exam_year_end_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public LocalDateTime getExamYearEndDate() {
        return examYearEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.exam_year_end_date
     *
     * @param examYearEndDate the value for exam_date.exam_year_end_date
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setExamYearEndDate(LocalDateTime examYearEndDate) {
        this.examYearEndDate = examYearEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.is_delete
     *
     * @return the value of exam_date.is_delete
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.is_delete
     *
     * @param isDelete the value for exam_date.is_delete
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}