package com.herbertgao.telegram.database.entity;

public class ExamDateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_date.id
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_date.id
     *
     * @return the value of exam_date.id
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_date.id
     *
     * @param id the value for exam_date.id
     *
     * @mbg.generated Thu Sep 05 13:16:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}