package com.herbertgao.telegram.database.entity;

public class UserTemplateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.id
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.id
     *
     * @return the value of user_template.id
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.id
     *
     * @param id the value for user_template.id
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }
}