package com.herbertgao.telegram.database.entity;

public class UserBindExam extends UserBindExamKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind_exam.user_id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind_exam.exam_username
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    private String examUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind_exam.exam_id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind_exam.is_delete
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind_exam.user_id
     *
     * @return the value of user_bind_exam.user_id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind_exam.user_id
     *
     * @param userId the value for user_bind_exam.user_id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind_exam.exam_username
     *
     * @return the value of user_bind_exam.exam_username
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public String getExamUsername() {
        return examUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind_exam.exam_username
     *
     * @param examUsername the value for user_bind_exam.exam_username
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public void setExamUsername(String examUsername) {
        this.examUsername = examUsername == null ? null : examUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind_exam.exam_id
     *
     * @return the value of user_bind_exam.exam_id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind_exam.exam_id
     *
     * @param examId the value for user_bind_exam.exam_id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind_exam.is_delete
     *
     * @return the value of user_bind_exam.is_delete
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind_exam.is_delete
     *
     * @param isDelete the value for user_bind_exam.is_delete
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}