package com.herbertgao.telegram.database.entity;

public class UserBindExamKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind_exam.id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind_exam.id
     *
     * @return the value of user_bind_exam.id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind_exam.id
     *
     * @param id the value for user_bind_exam.id
     *
     * @mbg.generated Fri Aug 30 23:58:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}