package com.herbertgao.telegram.database.mapper;

import com.herbertgao.telegram.database.entity.UserTemplate;
import com.herbertgao.telegram.database.entity.UserTemplateExample;
import com.herbertgao.telegram.database.entity.UserTemplateKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @SelectProvider(type=UserTemplateSqlProvider.class, method="countByExample")
    long countByExample(UserTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @DeleteProvider(type=UserTemplateSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @Delete({
        "delete from user_template",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(UserTemplateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @Insert({
        "insert into user_template (id, user_id, ",
        "template_name, template_content)",
        "values (#{id,jdbcType=BIGINT}, #{userId,jdbcType=INTEGER}, ",
        "#{templateName,jdbcType=VARCHAR}, #{templateContent,jdbcType=VARCHAR})"
    })
    int insert(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @InsertProvider(type=UserTemplateSqlProvider.class, method="insertSelective")
    int insertSelective(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @SelectProvider(type=UserTemplateSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="template_name", property="templateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="template_content", property="templateContent", jdbcType=JdbcType.VARCHAR)
    })
    List<UserTemplate> selectByExample(UserTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @Select({
        "select",
        "id, user_id, template_name, template_content",
        "from user_template",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="template_name", property="templateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="template_content", property="templateContent", jdbcType=JdbcType.VARCHAR)
    })
    UserTemplate selectByPrimaryKey(UserTemplateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @UpdateProvider(type=UserTemplateSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserTemplate record, @Param("example") UserTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @UpdateProvider(type=UserTemplateSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserTemplate record, @Param("example") UserTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @UpdateProvider(type=UserTemplateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbg.generated Wed Apr 08 18:12:30 CST 2020
     */
    @Update({
        "update user_template",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "template_name = #{templateName,jdbcType=VARCHAR},",
          "template_content = #{templateContent,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserTemplate record);
}